### ISSUE TITLE
Exports are determined at install time

### ISSUE THREAD

**Issue by gaborcsardi** [mllg/backports#12]
Which is not ideal if somebody has multiple R versions and leads to hard to debug problems.

If `backports` could export the functions at load time somehow, that would be great.

**Comment by mllg** [comment]
1. Note that using packages build against a different R version is in general somewhat risky. This is not tested and discouraged by R core (according to Uwe Ligges). `backports` should probably warn about that.
2. Using load-time exports was my first attempt for backports, but I encountered several problems silencing R CMD check. I'll check again if I can find a working solution (suggestions welcome!).
3. If it helps, I can re-license the package under MIT or BSD.

**Comment by gaborcsardi** [comment]
> 1. Note that using packages build against a different R version is in general somewhat risky. This is not tested and discouraged by R core (according to Uwe Ligges). backports should probably warn about that.

True in general, but for simple packages without compiled code and build-time dependencies, it is usually fine.

> Using load-time exports was my first attempt for backports, but I encountered several problems silencing R CMD check. I'll check again if I can find a working solution (suggestions welcome!).

@lionel- did this:
https://github.com/hadley/devtools/pull/1508/commits/b04266d94366603fb624afa4d0db77ac5258b939#diff-434efa1e44ee83a15481ea98901eaaef

I don't know if it is directly usable for you.

> If it helps, I can re-license the package under MIT or BSD.

I don't mind the license as long as I use the package. I would mind it if I had to / wanted to copy code over from it. Btw. I am not sure if you can license it under non-GPL, if you already looked at the R code you are re-implementing.

**Comment by lionel-** [comment]
I don't know about the CMD check issue, but you could keep the install time export just like it is and then provide an `import()` function that would take the relevant functions from your namespace and assign them in a supplied environment (converted with `asNamespace()` if a string).

**Comment by lionel-** [comment]
The `import()` function would do the relevant version check for each requested backport. If no argument is supplied, it would conditionally import all backports.

**Comment by mllg** [comment]
There is now an `import` function [here](https://github.com/mllg/backports/blob/master/R/import.R).
I decided to not rely on version numbers because R core is not very disciplined in adding new functionality only in major releases. Instead, the import function only assigns the backport in the package namespace iff R does not provide it. 

Let me know if this works for you.

**Comment by gaborcsardi** [comment]
Cool, thanks!

**Comment by mllg** [comment]
Released on CRAN. Using `import` is now the recommended way to use backports.

**Comment by gaborcsardi** [comment]
@mllg Great, thanks!
