### ISSUE TITLE
apparent conflict with gamlss

### ISSUE THREAD

**Issue by barryef** [mllg/backports#9]
Hi, I just tried to install gamlass into my miniconda library using conda and got the following error message. I don't understand what the problem is. I've installed many r packages without problem.

Please advise.

Thank you!

$ conda install --channel https://conda.anaconda.org/bioconda r-gamlss
Fetching package metadata ...........
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - r-backports
  - r-gamlss -> r 3.3.1* -> r-base 3.3.1
Use "conda info <package>" to see the dependencies for each package.

**Comment by barryef** [comment]
PS - I'm loading gamlss with conda so that I can use it in an R-powered Jupyter notebook.

**Comment by mllg** [comment]
I don't see any problems loading both packages in the same R session:
```{r}
library(backports); library(gamlss)
Loading required package: splines
Loading required package: gamlss.data
Loading required package: gamlss.dist
Loading required package: MASS
Loading required package: nlme
Loading required package: parallel
 **********   GAMLSS Version 5.0-1  ********** 
For more on GAMLSS look at http://www.gamlss.org/
Type gamlssNews() to see new features/changes/bug fixes.
```
In fact, there is no connection between backports and gamlss. I don't know conda, but I guess the output is misleading and you probably just have to install a different R version for gamlss?

**Comment by mllg** [comment]
Can't fix, would need more info.
